receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
